server {
    listen 80;

    root /usr/share/nginx/html;
    index pages/index.html;

    # map / as /pages/index.html
    location = / {
        try_files /pages/index.html =404;
    }

    # map /download to /pages/download.html
    location = /download {
        try_files /pages/download.html =404;
    }

    # for all other requests serve normally
    location / {
        try_files $uri $uri/ =404;
    }

    # serve static stuff
    location ~* \.(html|css|js|png|jpg|jpeg|gif|svg|ico)$ {
        expires 1d;
        access_log off;
    }
}